language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
install: pip install coveralls
script:
    - coverage run test/test_basic.py
    - coverage run test/test_utils.py
branches:
  only:
    - master
after_success:
  - coveralls