language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
install: pip install coveralls lxml
script:
    - coverage run -m unittest discover test/
branches:
  only:
    - master
after_success:
  - coveralls