language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
install:
pip install coveralls
script:
  coverage run --source=rosterpy test/test_basic.py
branches:
  only:
    - master
after_success:
  - coveralls